/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const aidRegExp: string
export function genAid(t: number): string
export function parseAid(id: string): { date: Date; }
export function checkHttps(url: string, nodeEnv?: string | undefined | null): boolean
export function correctFilename(filename: string, ext?: string | undefined | null): string
export const L_CHARS: string
export function secureRndstr(length?: number | undefined | null, chars?: string | undefined | null): string
export interface Acct {
  username: string
  host?: string
}
export function parse(acct: string): { username: string; host: string | null; }
export function toString(acct: Acct): string
